export const SET_PRODUCTS = "SET_PRODUCTS"
export const SET_PRODUCTS_FAIL = "SET_PRODUCTS_FAIL"
export const SET_DETAIL_STATE = "SET_DETAIL_STATE"
export const SET_PRODUCT_FILTER = "SET_PRODUCT_FILTER"
export const GET_COLORS = "GET_COLORS";
export const GET_BRANDS = "GET_BRANDS";
export const SET_BRANDS_FAIL = "SET_BRANDS_FAIL"
export const SET_COLORS_FAIL = "SET_COLORS_FAIL"
export const GET_CHECKFILTER_PRODUCTS = "GET_CHECKFILTER_PRODUCTS"
export const SET_CHECKFILTER_PRODUCTS = "SET_CHECKFILTER_PRODUCTS"
export const FAILED_FILTER_PRODUCTS = "FAILED_CHECKFILTER_PRODUCTS"

export const GET_PRODUCTS_INIT = "GET_PRODUCTS_INIT";
export const GET_PRODUCTS_SUCCESS = "GET_PRODUCTS_SUCCESS";
export const GET_PRODUCTS_FAILED = "GET_PRODUCTS_FAILED"

export const GET_PRODUCT_DETAIL = "GET_PRODUCT_DETAIL"


/// auth
export const LOGIN_SUCCESS = "LOGIN_SUCCESS"
export const LOGIN_FAIL= "LOGIN_FAIL"
export const GETAUTH = "GETAUTH"; 
/// INTERFACES ACTIONSS /// 

export const SET_PRODUCT_IMG = "SET_PRODUCT_IMG";
export const SET_PRODUCTS_IMG_FAIL = "SET_PRODUCTS_IMG_FAIL"

export const PURCHASE_BURGER_START = "PURCHASE_BURGER_START";


